### ISSUE TITLE
Example SEO field plugin referenced in readme no longer exists

### ISSUE THREAD

**Issue by SmartyP** [storyblok/custom-app-examples#24]
The primary readme references a `Seo Data App` example, however when you visit the link (https://github.com/storyblok/custom-app-examples/tree/main/seo-data-app) it gives a 404 / missing error. It appears this example no longer exists and the readme needs updating to remove it, or to reference a new example.

**Comment by eunjae-lee** [comment]
Hi @SmartyP thanks for creating this issue. You're right. The example has been removed and the README was outdated.

You could still find the source code if you're interested: https://github.com/storyblok/custom-app-examples/pull/20
